 
     CREATE TABLE "CANDIDATO"."FILE_" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(500 BYTE), 
	"FILESIZE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE UNIQUE INDEX "CANDIDATO"."FILE__PK" ON "CANDIDATO"."FILE_" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
--------------------------------------------------------
--  DDL for Trigger FILE_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CANDIDATO"."FILE_ON_INSERT" 
  BEFORE INSERT ON file_
  FOR EACH ROW
BEGIN
  SELECT file_sequence.nextval
  INTO :new.id
  FROM dual;
END;
/
ALTER TRIGGER "CANDIDATO"."FILE_ON_INSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table FILE_
--------------------------------------------------------

  ALTER TABLE "CANDIDATO"."FILE_" ADD CONSTRAINT "FILE__PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CANDIDATO"."FILE_" MODIFY ("FILESIZE" NOT NULL ENABLE);
  ALTER TABLE "CANDIDATO"."FILE_" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CANDIDATO"."FILE_" MODIFY ("ID" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  Insert File
--------------------------------------------------------
  
  INSERT INTO File_ (name, filesize)
   VALUES ('FileXPTO', 850);